-- ============================================================
-- 批量导入新概念一/二分课词表到 lesson_words
-- 新概念一: 72 课 / 895 词 —— 按“对”合并：
--   单课(课文)+配对双课(练习)的单词全部挂到单课号下，登记只填单课号
-- 新概念二: 96 课 / 497 词
-- ① 新概念一为覆盖导入（合并版数据，冲掉本表里旧的 NCE1 行）
-- ② 新概念二不覆盖（保护手工录入过的课，如 L27）
-- 生成时间: 2026-09-15
-- ============================================================

-- ① 新概念一（覆盖）
insert into lesson_words (family_id, book, lesson_no, words)
select f.id, v.book, v.lesson_no, v.words::jsonb
from families f
join (values
  ('新概念一', 1, '["excuse 原谅","me 我(宾格)","yes 是的","is 动词现在时第三人称单数","this 这","your 你的，你们的","handbag (女用)手提包","pardon 原谅，请再说一遍","it 它","thank you 感谢你(们)","very much 非常地","pen 钢笔","pencil 铅笔","book 书","watch 手表","coat 上衣，外衣","dress 连衣裙","skirt 裙子","shirt 衬衣","car 小汽车","house 房子"]'::text),
  ('新概念一', 3, '["umbrella 伞","please 请","here 这里","my 我的","ticket 票","number 号码","five 五","sorry 对不起的","sir 先生","cloakroom 衣帽存放处","suit 一套衣服","school 学校","teacher 老师","son 儿子","daughter 女儿"]'::text),
  ('新概念一', 5, '["Mr. 先生","good 好","morning 早晨","Miss 小姐","new 新的","student 学生","French 法国人","German 德国人","nice 美好的","meet 遇见","Japanese 日本人","Korean 韩国人","Chinese 中国人","too 也","make (产品的)牌号","Swedish 瑞典的","English 英国的","American 美国的","Italian 意大利的","Volvo 沃尔沃","Peugeot 标致","Mercedes 梅赛德斯","Toyota 丰田","Daewoo 大宇","Mini 迷你","Ford 福特","Fiat 菲亚特"]'::text),
  ('新概念一', 7, '["I 我","am 动词现在时第一人称单数","are 动词现在时复数","name 名字","what 什么","nationality 国籍","job 工作","keyboard 电脑键盘","operator 操作人员","engineer 工程师","policeman 警察","policewoman 女警察","taxi driver 出租汽车司机","air hostess 空中小姐","postman 邮递员","nurse 护士","mechanic 机械师","hairdresser 理发师","housewife 家庭妇女","milkman 送牛奶的人"]'::text),
  ('新概念一', 9, '["hello 喂(表示问候)","hi 喂，嗨","how 怎样","today 今天","well 身体好","fine 美好的","thanks 谢谢","goodbye 再见","see 见","fat 胖的","woman 女人","thin 瘦的","tall 高的","short 矮的","dirty 脏的","clean 干净的","hot 热的","cold 冷的","old 老的","young 年轻的","busy 忙的","lazy 懒的"]'::text),
  ('新概念一', 11, '["whose 谁的","blue 蓝色的","perhaps 大概","white 白色的","catch 抓住","father 父亲","mother 母亲","blouse 女衬衫","sister 姐，妹","tie 领带","brother 兄，弟","his 他的","her 她的"]'::text),
  ('新概念一', 13, '["colour 颜色","green 绿色","come 来","upstairs 楼上","smart 时髦的，巧妙的","hat 帽子","same 相同的","lovely 可爱的，秀丽的","case 箱子","carpet 地毯","dog 狗"]'::text),
  ('新概念一', 15, '["Customs 海关","officer 官员","girl 女孩，姑娘","Danish 丹麦人","friend 朋友","Norwegian 挪威人","passport 护照","brown 棕色的","tourist 旅游者","Russian 俄罗斯人","Dutch 荷兰人","these 这些(this的复数)","red 红色的","grey 灰色的","yellow 黄色的","black 黑色的","orange 橘黄色的"]'::text),
  ('新概念一', 17, '["employee 雇员","hard-working 勤奋的","sales reps 推销员","man 男人","office 办公室","assistant 助手"]'::text),
  ('新概念一', 19, '["matter 事情","children 孩子们(child 的复数)","tired 累，疲乏","boy 男孩","thirsty 渴","mum 妈妈(儿语)","sit down 坐下","right 好，可以","ice cream 冰淇淋","big 大的","small 小的","open 开着的","shut 关着的","light 轻的","heavy 重的","long 长的","shoe 鞋子","grandfather 祖父，外祖父","grandmother 祖母，外祖母"]'::text),
  ('新概念一', 21, '["give 给","one 一个","which 哪一个","empty 空的","full 满的","large 大的","little 小的","sharp 尖的，锋利的","small 小的","big 大的","blunt 钝的","box 盒子，箱子","glass 杯子","cup 茶杯","bottle 瓶子","tin 罐头","knife 刀子","fork 叉子"]'::text),
  ('新概念一', 23, '["on 在…之上","shelf 架子，搁板","desk 课桌","table 桌子","plate 盘子","cupboard 食橱","cigarette 香烟","television 电视机","floor 地板","dressing table 梳妆台","magazine 杂志","bed 床","newspaper 报纸","stereo 立体声音响"]'::text),
  ('新概念一', 25, '["Mrs. 夫人","kitchen 厨房","refrigerator 电冰箱","right 右边","electric 带电的，可通电的","left 左边","cooker 炉子，炊具","middle 中间","of (属于)…的","room 房间","cup 杯子","where 在哪里","in 在…里"]'::text),
  ('新概念一', 27, '["living room 客厅","near 靠近","window 窗户","armchair 手扶椅","door 门","picture 图画","wall 墙","trousers (复数)长裤"]'::text),
  ('新概念一', 29, '["shut 关门","bedroom 卧室","untidy 乱，不整齐","must 必须，应该","open 打开","air 使…通风，换换空气","put 放置","clothes 衣服","wardrobe 大衣柜","dust 掸掉灰尘","sweep 扫","empty 倒空，使…变空","read 读","sharpen 削尖，使锋利","take off 脱掉","turn on 开(电灯)"]'::text),
  ('新概念一', 31, '["garden 花园","under 在…之下","tree 树","climb 爬，攀登","who 谁","run 跑","grass 草，草地","after 在…之后","cat 猫","type 打字","letter 信","basket 篮子","eat 吃","bone 骨头","clean 清洗","tooth 牙齿","cook 做(饭菜)","milk 牛奶","meal 饭，一顿饭","drink 喝","tap (水)龙头"]'::text),
  ('新概念一', 33, '["day 日子","cloud 云","sky 天空","sun 太阳","shine 照耀","with 和…在一起","family 家庭(成员)","walk 走路，步行","over 跨越，在…之上","bridge 桥","boat 船","river 河","ship 轮船","aeroplane 飞机","fly 飞","sleep 睡觉","shave 刮脸","cry 哭，喊","wash 洗","wait 等","jump 跳"]'::text),
  ('新概念一', 35, '["photograph 照片","village 村庄","valley 山谷","between 在…之间","hill 小山","another 另一个","wife 妻子","along 沿着","bank 河岸","water 水","swim 游泳","across 横过","building 大楼，建筑物","park 公园","into 进入","beside 在…旁","off 离开"]'::text),
  ('新概念一', 37, '["work 工作","hard 努力地","make 做","bookcase 书橱，书架","hammer 锤子","paint 上漆，涂","pink 粉红色","favourite 最喜欢的","homework 作业","listen 听","dish 盘子，碟子"]'::text),
  ('新概念一', 39, '["front 前面","in front of 在…之前","careful 小心的，仔细的","vase 花瓶","drop 掉下","flower 花","show 给…看","send 送给","take 带给"]'::text),
  ('新概念一', 41, '["cheese 乳酪，干酪","bread 面包","soap 肥皂","chocolate 巧克力","sugar 糖","coffee 咖啡","tea 茶","tobacco 烟草，烟丝","bird 鸟","any 一些","some 一些"]'::text),
  ('新概念一', 43, '["of course 当然","kettle 水壶","behind 在…后面","teapot 茶壶","now 现在，此刻","find 找到","boil 沸腾，开"]'::text),
  ('新概念一', 45, '["can 能够","boss 老板，上司","minute 分(钟)","ask 请求，要求","handwriting 书写","terrible 糟糕的，可怕的","lift 拿起，搬起，举起","cake 饼，蛋糕","biscuit 饼干"]'::text),
  ('新概念一', 47, '["like 喜欢，想要","want 想","fresh 新鲜的","egg 鸡蛋","butter 黄油","pure 纯净的","honey 蜂蜜","ripe 成熟的","banana 香蕉","jam 果酱","sweet 甜的","orange 橙","Scotch whisky 苏格兰威士忌","choice 上等的，精选的","apple 苹果","wine 酒，果酒","beer 啤酒","blackboard 黑板"]'::text),
  ('新概念一', 49, '["butcher 卖肉的","meat (食用)肉","beef 牛肉","lamb 羔羊肉","husband 丈夫","steak 牛排","mince 肉馅，绞肉","chicken 鸡","tell 告诉","truth 实情","either 也(用于否定句)","tomato 西红柿","potato 土豆","cabbage 卷心菜","lettuce 莴苣","pea 豌豆","bean 豆角","pear 梨","grape 葡萄","peach 桃"]'::text),
  ('新概念一', 51, '["Greece 希腊","climate 气候","country 国家","pleasant 宜人的","weather 天气","spring 春季","windy 有风的","warm 温暖的","rain 下雨","sometimes 有时","summer 夏天","autumn 秋天","winter 冬天","snow 下雪","January 1月","February 2月","March 3月","April 4月","May 5月","June 6月","July 7月","August 8月","September 9月","October 10月","November 11月","December 12月","the U.S. 美国","Brazil 巴西","Holland 荷兰","England 英国","France 法国","Germany 德国","Italy 意大利","Norway 挪威","Russia 俄罗斯","Spain 西班牙","Sweden 瑞典"]'::text),
  ('新概念一', 53, '["mild 温和的，温暖的","always 总是","north 北方","east 东方","wet 潮湿的","west 西方","south 南方","season 季节","best 最","night 夜晚","rise 升起","early 早","set (太阳)落下去","late 晚，迟","interesting 有趣的，有意思的","subject 话题","conversation 谈话","Australia 澳大利亚","Australian 澳大利亚人","Austria 奥地利","Austrian 奥地利人","Canada 加拿大","Canadian 加拿大人","China 中国","Finland 芬兰","Finnish 芬兰人","India 印度","Indian 印度人","Japan 日本","Nigeria 尼日利亚","Nigerian 尼日利亚人","Turkey 土耳其","Turkish 土耳其人","Korea 韩国","Polish 波兰人","Poland 波兰","Thai 泰国人","Thailand 泰国"]'::text),
  ('新概念一', 55, '["live 住，生活","stay 呆在，停留","home 家 ad.在家，到家","housework 家务","lunch 午饭","afternoon 下午","usually 通常","together 一起","evening 晚上","arrive 到达","night 夜间"]'::text),
  ('新概念一', 57, '["o''clock 点钟","shop 商店","moment 片刻，瞬间"]'::text),
  ('新概念一', 59, '["envelope 信封","writing paper 信纸","shop assistant 售货员","size 尺寸，尺码，大小","pad 信笺簿","glue 胶水","chalk 粉笔","change 零钱，找给的钱"]'::text),
  ('新概念一', 61, '["feel 感觉","look 看(起来)","must 必须","call 叫，请","doctor 医生","telephone 电话","remember 记得，记住","mouth 嘴","tongue 舌头","bad 坏的，严重的","cold 感冒","news 消息","headache 头痛","aspirin 阿斯匹林","earache 耳痛","toothache 牙痛","dentist 牙医","stomach ache 胃痛","medicine 药","temperature 温度","flu 流行性感冒","measles 麻疹","mumps 腮腺炎"]'::text),
  ('新概念一', 63, '["better 形容词well的比较级","certainly 当然","get up 起床","yet 还，仍","rich 油腻的","food 食物","remain 保持，继续","play 玩","match 火柴","talk 谈话","library 图书馆","drive 开车","so 如此地","quickly 快地","lean out of 身体探出","break 打破"]'::text),
  ('新概念一', 65, '["Dad 爸(儿语)","key 钥匙","baby 婴儿","hear 听见","enjoy 玩得快活","yourself 你自己","ourselves 我们自己","myself 我自己","themselves 他们自己","himself 他自己","herself 她自己"]'::text),
  ('新概念一', 67, '["greengrocer 蔬菜水果零售商","absent 缺席的","Monday 星期一","Tuesday 星期二","Wednesday 星期三","Thursday 星期四","keep (身体健康)处于(状况)","spend 度过","weekend 周末","Friday 星期五","Saturday 星期六","Sunday 星期日","country 乡村","lucky 幸运的","church 教堂","dairy 乳品店","baker 面包师傅","grocer 食品杂货商"]'::text),
  ('新概念一', 69, '["year 年","race 比赛","town 城镇","crowd 人群","stand 站立","exciting 使人激动的","just 正好，恰好","finish 结尾，结束","winner 获胜者","behind prop. 在…之后","way 路途"]'::text),
  ('新概念一', 71, '["awful 让人讨厌的，坏的","telephone 打电话","time 次(数)","answer 接(电话)","last 最后的，前一次的","phone 电话(=telephone)","again 又一次地","say 说"]'::text),
  ('新概念一', 73, '["week 周","London 伦敦","suddenly 突然地","bus stop 公共汽车车站","smile 微笑","pleasantly 愉快地","understand 懂，明白","speak 讲，说","hand 手","pocket 衣袋","phrasebook 短语手册，常用语手册","phrase 短语","slowly 缓慢地","hurriedly 匆忙地","cut 割，切","thirstily 口渴地","go 走","greet 问候，找招呼"]'::text),
  ('新概念一', 75, '["ago 以前","buy 买","pair 双，对","fashion (服装的)流行式样","uncomfortable 不舒服的","wear 穿着"]'::text),
  ('新概念一', 77, '["appointment 约会，预约","urgent 紧急的，急迫的","till 直到…为止"]'::text),
  ('新概念一', 79, '["shopping 购物","list 单子","vegetable 蔬菜","need 需要","hope 希望","thing 事情","money 钱","groceries 食品杂货","fruit 水果","stationery 文具","newsagent 报刊零售人","chemist 化剂师，化学家"]'::text),
  ('新概念一', 81, '["bath 洗澡","nearly 几乎，将近","ready 准备好的，完好的","dinner 正餐，晚餐","restaurant 饭馆，餐馆","roast 烤的","breakfast 早饭","haircut 理发","party 聚会","holiday 假日"]'::text),
  ('新概念一', 83, '["mess 杂乱，凌乱","pack 包装，打包，装箱","suitcase 手提箱","leave 离开","already 已经"]'::text),
  ('新概念一', 85, '["Paris 巴黎","cinema 电影院","film 电影","beautiful 漂亮的","city 城市","never 从来没有","ever 在任何时候"]'::text),
  ('新概念一', 87, '["attendant 接待员","bring 带来，送来","garage 车库，汽车修理厂","crash 碰撞","lamp-post 灯杆","repair 修理","try 努力，设法"]'::text),
  ('新概念一', 89, '["believe 相信，认为","may ( 用于请求许可)可以","how long 多长","since 自从","why 为什么","sell 卖，出售","because 因为","retire 退休","cost 花费","pound 英镑","worth 值…钱","penny 便士"]'::text),
  ('新概念一', 91, '["still 还，仍旧","move 搬家","miss 想念，思念","neighbour 邻居","person 人","people 人们","poor 可怜的"]'::text),
  ('新概念一', 93, '["pilot 飞行员","return 返回","New York 纽约","Tokyo 东京","Madrid 马德里","fly 飞行","Athens 雅典","Berlin 柏林","Bombay 孟买","Geneva 日内瓦","Moscow 莫斯科","Rome 罗马","Seoul 汉城","Stockholm 斯德哥尔摩","Sydney 悉尼"]'::text),
  ('新概念一', 95, '["return 往返","train 火车","platform 站台","plenty 大量","bar 酒吧","station 车站，火车站","catch 赶上","miss 错过"]'::text),
  ('新概念一', 97, '["leave 遗留","describe 描述","zip 拉链","label 标签","handle 提手，把手","address 地址","pence 的复数形式","belong 属于"]'::text),
  ('新概念一', 99, '["ow 哎哟","slip 滑倒，滑了一脚","fall 落下，跌倒","downstairs 下楼","hurt 伤，伤害，疼痛","back 背","stand up 起立，站起来","help 帮助","at once 立即","sure 一定的，确信的","X-ray 光透视"]'::text),
  ('新概念一', 101, '["Scotland 苏格兰(英国)","card 明信片","youth 青年","hostel 招待所，旅馆","association 协会","soon 不久","write 写"]'::text),
  ('新概念一', 103, '["exam 考试","pass 及格，通过","mathematics 数学","question 问题","easy 容易的","enough 足够地","paper 考卷","fail 未及格，失败","answer 回答","mark 分数","rest 其他的东西","difficult 困难的","hate 讨厌","low 低的","cheer 振作，振奋","guy 家伙，人","top 上方，顶部","clever 聪明的","stupid 笨的","cheap 便宜的","expensive 贵的","fresh 新鲜的","stale 变馊的","loud 大声的","high 高的","hard 硬的","sweet 甜的","soft 软的","sour 酸的"]'::text),
  ('新概念一', 105, '["spell 拼写","intelligent 聪明的，有智慧的","mistake 错误","present 礼物","dictionary 词典","carry 携带","correct 改正，纠正"]'::text),
  ('新概念一', 107, '["madam 夫人，女士(对妇女的尊称)","as well 同样","suit 适于","pretty 漂亮的"]'::text),
  ('新概念一', 109, '["idea 主意","a little 少许(用于不可数名词之前)","teaspoonful 一满茶匙","less a.(little 的比较级)校少的，更小的","pity 遗憾","instead 代替","advice 建议，忠告","most a.(many,much 的最高级)最多的","least a.(little 的最高级)最小的，最少的","best a.(good 的最高级)最好的","worse a.(bad 的比较级)更坏的","worst a.(bad 的最高级)最坏的"]'::text),
  ('新概念一', 111, '["model 型号，式样","afford 付得起(钱)","deposit 预付定金","instalment 分期付款","price 价格","millionaire 百万富翁"]'::text),
  ('新概念一', 113, '["conductor 售票员","fare 车费，车票","change 兑换(钱)","note 纸币","passenger 乘客","none 没有任何东西","neither 也不","get off 下车","tramp 流浪汉","except 除…外"]'::text),
  ('新概念一', 115, '["anyone (用于疑问句，否定式)任何人","knock 敲，打","everything 一切事物","quiet 宁静的，安静的","impossible 不可能的","invite 邀请","anything 任何东西","nothing 什么也没有","lemonade 柠檬水","joke 开玩笑","asleep 睡觉，睡着(用作表语)","glasses 眼镜"]'::text),
  ('新概念一', 117, '["dining room 饭厅","coin 硬币","mouth 嘴","swallow 吞下","later 后来","toilet 厕所，盥洗室","ring 响"]'::text),
  ('新概念一', 119, '["story 故事","happen 发生","thief 贼","enter 进入","dark 黑暗的","torch 手电筒","voice (说话的)声音","parrot 鹦鹉","exercise book 练习本"]'::text),
  ('新概念一', 121, '["customer 顾客","forget 忘记","manager 经理","serve 照应，服务，接待","counter 柜台","recognize 认识","road 路"]'::text),
  ('新概念一', 123, '["during 在…期间","trip 旅行","travel 旅行","offer 提供","job 工作","guess 猜","grow 长，让…生长","beard (下巴上的)胡子，络腮胡子","kitten 小猫"]'::text),
  ('新概念一', 125, '["water 浇水","terribly 非常","dry 干燥的，干的","nuisance 讨厌的东西或人","mean 意味着，意思是","surprise 惊奇，意外的事","immediately 立即地"]'::text),
  ('新概念一', 127, '["famous 著名的","actress 女演员","at least 至少","actor 男演员","read 通过阅读得知"]'::text),
  ('新概念一', 129, '["wave 招手","track 跑道","mile 英里","overtake 从后面超越，超车","speed 限速","dream 做梦，思想不集中","sign 标记，牌子","driving licence 驾驶执照","charge 罚款","darling 亲爱的(用作表示称呼)"]'::text),
  ('新概念一', 131, '["Egypt 埃及","abroad 国外","worry 担忧"]'::text),
  ('新概念一', 133, '["reporter 记者","sensational 爆炸性的，耸人听闻的","mink coat 貂皮大衣"]'::text),
  ('新概念一', 135, '["future 未来的","get married 结婚","hotel 饭店","latest 最新的","introduce 介绍"]'::text),
  ('新概念一', 137, '["football 足球","pool 赌注","win 赢","world 世界","poor 贫穷的","depend 依靠(on)"]'::text),
  ('新概念一', 139, '["extra 额外的","engineer 工程师","overseas 海外的，国外的","engineering 工程","company 公司","line 线路"]'::text),
  ('新概念一', 141, '["excited 兴奋的","get on 登上","middle-aged 中年的","opposite 在…对面","curiously 好奇地","funny 可笑的，滑稽的","powder 香粉","compact 带镜的化妆盒","kindly 和蔼地","ugly 丑陋的","amused 有趣的","smile 微笑","embarrassed 尴尬的，窘迫的","worried 担心，担忧","regularly 经常地，定期地"]'::text),
  ('新概念一', 143, '["surround 包围","wood 树林","beauty spot 风景点","hundred 百","city 城市","through 穿过","visitor 参观者，游客，来访者","tidy 整齐的","litter 杂乱的东西","place 放","throw 扔，抛","rubbish 垃圾","count 数，点","cover 覆盖","piece 碎片","tyre 轮胎","rusty 生锈的","among 在…之间","prosecute 依法处置"]'::text)
) as v(book, lesson_no, words) on true
on conflict (family_id, book, lesson_no) do update set words = excluded.words;

-- ② 新概念二（不覆盖已有）
insert into lesson_words (family_id, book, lesson_no, words)
select f.id, v.book, v.lesson_no, v.words::jsonb
from families f
join (values
  ('新概念二', 1, '["private adj. 私人的","conversation n. 谈话","theatre n. 剧场，戏院","seat n. 座位","play n. 戏","loudly adv. 大声地","angry adj. 生气的","angrily adv. 生气地","attention n. 注意","bear v. 容忍","business n. 事","rudely adv. 无礼地"]'::text),
  ('新概念二', 2, '["breakfast n. 早饭","lunch n. 午饭","outside adv. 外面","ring v. （铃）响","aunt n. 姑母，姨母","repeat v. 重复"]'::text),
  ('新概念二', 3, '["send v. 寄","postcard n. 明信片","spoil v. 使索然无味","museum n. 博物馆","public adj. 公共的","friendly adj. 友好的","waiter n. 服务员","lend v. 借出","decision n. 决定","whole adj. 整个的","single adj. 唯一的"]'::text),
  ('新概念二', 4, '["exciting adj. 令人兴奋的","receive v. 收到","firm n. 公司","different adj. 不同的","centre n. 中心","abroad adv. 在国外"]'::text),
  ('新概念二', 5, '["pigeon n. 鸽子","message n. 消息","cover v. 覆盖","distance n. 距离","request n. 请求","spare adj. 多余的","service n. 服务"]'::text),
  ('新概念二', 6, '["beggar n. 乞丐","pocket n. 口袋","knock v. 敲","ask for v. 要求","meal n. 一餐","call v. 拜访"]'::text),
  ('新概念二', 7, '["detective n. 侦探","airport n. 机场","expect v. 期待","valuable adj. 贵重的","guard v. 守卫","steal v. 偷","main adj. 主要的","precious adj. 珍贵的","parcel n. 包裹"]'::text),
  ('新概念二', 8, '["competition n. 比赛","neat adj. 整齐的","path n. 小路","wooden adj. 木制的","pool n. 水池"]'::text),
  ('新概念二', 9, '["welcome n. 欢迎","crowd n. 人群","gather v. 聚集","hand n. （钟表的）指针","shout v. 喊叫","refuse v. 拒绝","laugh v. 笑"]'::text),
  ('新概念二', 10, '["jazz n. 爵士乐","musical adj. 音乐的","instrument n. 乐器","clavichord n. 古钢琴","recently adv. 最近","damage v. 损坏","key n. 琴键","string n. 琴弦","shock v. 震惊","allow v. 允许","touch v. 触摸"]'::text),
  ('新概念二', 11, '["turn n. 行为","deserve v. 应得","lawyer n. 律师","bank n. 银行","salary n. 薪水","immediately adv. 立即"]'::text),
  ('新概念二', 12, '["luck n. 运气","captain n. 船长","sail v. 航行","harbour n. 港口","proud adj. 自豪的","important adj. 重要的"]'::text),
  ('新概念二', 13, '["group n. 小组","pop singer n. 流行歌手","club n. 俱乐部","performance n. 演出","occasion n. 场合"]'::text),
  ('新概念二', 14, '["amusing adj. 好笑的","experience n. 经历","wave v. 招手","lift n. 搭便车","reply v. 回答","language n. 语言","journey n. 旅行"]'::text),
  ('新概念二', 15, '["nervous adj. 紧张的","afford v. 负担得起","weak adj. 弱的","interrupt v. 打断"]'::text),
  ('新概念二', 16, '["park v. 停车","traffic n. 交通","sign n. 标牌","polite adj. 有礼貌的","fail v. 无效"]'::text),
  ('新概念二', 17, '["appear v. 出现","stage n. 舞台","bright adj. 鲜艳的","stocking n. 长筒袜","sock n. 短袜"]'::text),
  ('新概念二', 18, '["pub n. 酒馆","landlord n. 店主","bill n. 账单"]'::text),
  ('新概念二', 19, '["hurry v. 匆忙","ticket office n. 售票处","pity n. 遗憾","exclaim v. 大声说","return v. 退回","sadly adv. 悲伤地"]'::text),
  ('新概念二', 20, '["catch v. 抓住","fisherman n. 钓鱼人","boot n. 靴子","waste n. 浪费","realize v. 意识到"]'::text),
  ('新概念二', 21, '["mad adj. 发疯的","reason n. 原因","sum n. 金额","determined adj. 坚定的"]'::text),
  ('新概念二', 22, '["dream n. 梦","age n. 年龄","channel n. 海峡","throw v. 扔"]'::text),
  ('新概念二', 23, '["complete v. 完成","modern adj. 现代的","strange adj. 奇怪的","district n. 地区"]'::text),
  ('新概念二', 24, '["manager n. 经理","upset adj. 心烦的","sympathetic adj. 同情的","complain v. 抱怨","wicked adj. 邪恶的"]'::text),
  ('新概念二', 25, '["railway n. 铁路","several det. 几个","foreigner n. 外国人","wonder v. 想知道","platform n. 站台"]'::text),
  ('新概念二', 26, '["art n. 艺术","critic n. 评论家","paint v. 画","pretend v. 假装","pattern n. 图案","upside down adv. 上下颠倒地"]'::text),
  ('新概念二', 27, '["tent n. 帐篷","field n. 田地","smell v. 闻到","wonderful adj. 极好的","campfire n. 营火","creep v. 爬行","sleeping bag n. 睡袋","comfortable adj. 舒服的"]'::text),
  ('新概念二', 28, '["rare adj. 罕见的","ancient adj. 古代的","myth n. 神话","trouble n. 麻烦","effect n. 效果"]'::text),
  ('新概念二', 29, '["taxi n. 出租车","pilot n. 飞行员","plough v. 犁","lonely adj. 孤独的","block n. 街区"]'::text),
  ('新概念二', 30, '["polo n. 水球","waist n. 腰","towards prep. 朝","kick v. 踢"]'::text),
  ('新概念二', 31, '["success n. 成功","retire v. 退休","company n. 公司","bicycle n. 自行车","save v. 攒钱"]'::text),
  ('新概念二', 32, '["once adv. 曾经","temptation n. 诱惑","article n. 物品","wrap v. 包裹","arrest v. 逮捕"]'::text),
  ('新概念二', 33, '["darkness n. 黑暗","explain v. 解释","coast n. 海岸","storm n. 暴风雨","cliff n. 悬崖","struggle v. 挣扎","hospital n. 医院"]'::text),
  ('新概念二', 34, '["station n. 车站","most adv. 最"]'::text),
  ('新概念二', 35, '["while conj. 当……时","regret v. 后悔","far adv. 远","rush v. 冲","act v. 行动"]'::text),
  ('新概念二', 36, '["record n. 纪录","strong adj. 强壮的","swimmer n. 游泳者","succeed v. 成功","train v. 训练","anxiously adv. 焦急地"]'::text),
  ('新概念二', 37, '["Olympic adj. 奥运的","hold v. 举办","government n. 政府","immense adj. 巨大的","stadium n. 体育场","standard n. 标准"]'::text),
  ('新概念二', 38, '["except prep. 除了","Mediterranean adj. 地中海的","complain v. 抱怨","continually adv. 不断地","bitterly adv. 刺骨地"]'::text),
  ('新概念二', 39, '["operation n. 手术","surgeon n. 外科医生","following adj. 接下来的","patient n. 病人","alone adj. 独自的"]'::text),
  ('新概念二', 40, '["host n. 主人","hostess n. 女主人","interrupt v. 打断","point v. 指","rudely adv. 无礼地"]'::text),
  ('新概念二', 41, '["rude adj. 粗鲁的","mirror n. 镜子","hole n. 洞","remark n. 评论"]'::text),
  ('新概念二', 42, '["musical adj. 精通音乐的","market n. 市场","snake n. 蛇","pipe n. 管子","tune n. 曲子"]'::text),
  ('新概念二', 43, '["pole n. 极","flight n. 飞行","explorer n. 探险家","lie v. 处于","serious adj. 严重的","point n. 地点"]'::text),
  ('新概念二', 44, '["forest n. 森林","risk n. 冒险","picnic n. 野餐","edge n. 边缘","strap n. 带子"]'::text),
  ('新概念二', 45, '["clear adj. 清白的","conscience n. 良心","wallet n. 钱包","savings n. 存款","villager n. 村民"]'::text),
  ('新概念二', 46, '["unload v. 卸货","wooden adj. 木制的","extremely adv. 极其","occur v. 发生"]'::text),
  ('新概念二', 47, '["thirsty adj. 渴的","ghost n. 鬼","inn n. 小旅馆","shake v. 摇动","accept v. 接受","furniture n. 家具"]'::text),
  ('新概念二', 48, '["pull v. 拉","cotton n. 棉花","collect v. 收集","nod v. 点头","calm adj. 镇静的"]'::text),
  ('新概念二', 49, '["tired adj. 疲倦的","real adj. 真正的","owner n. 主人","spring n. 弹簧","mattress n. 床垫","gust n. 一阵风","sweep v. 扫"]'::text),
  ('新概念二', 50, '["ride n. 旅行","excitedly adv. 兴奋地","suppose v. 假设","wave v. 招手"]'::text),
  ('新概念二', 51, '["reward n. 报酬","virtue n. 美德","diet n. 节食","forbid v. 禁止","hurriedly adv. 匆忙地","embarrass v. 使尴尬"]'::text),
  ('新概念二', 52, '["temporarily adv. 暂时地","inch n. 英寸","space n. 空间","actually adv. 实际上"]'::text),
  ('新概念二', 53, '["hot adj. 热的","fire brigade n. 消防队","headquarters n. 总部","discovery n. 发现"]'::text),
  ('新概念二', 54, '["sticky adj. 粘的","finger n. 手指","pie n. 馅饼","mix v. 混合","pastry n. 面糊","annoying adj. 恼人的"]'::text),
  ('新概念二', 55, '["gold n. 金子","mine n. 矿","treasure n. 财宝","revealer n. 探测器","bury v. 埋"]'::text),
  ('新概念二', 56, '["sound n. 声音","excitement n. 激动","handsome adj. 漂亮的","wheel n. 轮子","explosion n. 爆炸"]'::text),
  ('新概念二', 57, '["madam n. 夫人","jeans n. 牛仔裤","hesitate v. 犹豫","serve v. 服务","scorn n. 蔑视","punish v. 惩罚"]'::text),
  ('新概念二', 58, '["blessing n. 福气","disguise n. 伪装","tiny adj. 微小的","possess v. 拥有","cursed adj. 可恨的"]'::text),
  ('新概念二', 59, '["bark v. 吠叫","press v. 按","paw n. 爪子","latch n. 门闩"]'::text),
  ('新概念二', 60, '["future n. 未来","fair n. 集市","fortune-teller n. 算命师","crystal n. 水晶","relation n. 亲属","impatiently adv. 不耐烦地"]'::text),
  ('新概念二', 61, '["Hubble n. 哈勃","telescope n. 望远镜","launch v. 发射","space n. 太空","billion num. 十亿"]'::text),
  ('新概念二', 62, '["control v. 控制","smoke n. 烟","desolate adj. 荒凉的","threaten v. 威胁","destroy v. 毁坏"]'::text),
  ('新概念二', 63, '["circle n. 圈子","royal adj. 皇家的","amuse v. 逗乐","globe n. 地球"]'::text),
  ('新概念二', 64, '["tunnel n. 隧道","port n. 港口","ventilate v. 通风","layer n. 层","beneath prep. 在下方"]'::text),
  ('新概念二', 65, '["versus prep. 对","circus n. 马戏团","ought v. 应该","weigh v. 重"]'::text),
  ('新概念二', 66, '["sweet adj. 甜的","honey n. 蜂蜜","combine v. 结合","wreck n. 残骸","swarm n. 群"]'::text),
  ('新概念二', 67, '["volcano n. 火山","active adj. 活跃的","erupt v. 喷发","violent adj. 猛烈的","manage v. 设法","alive adj. 活着的"]'::text),
  ('新概念二', 68, '["persistent adj. 坚持的","avoid v. 避免","insist v. 坚持","matter n. 事情"]'::text),
  ('新概念二', 69, '["murder n. 谋杀","instruct v. 命令","deliver v. 递送","confirm v. 确认"]'::text),
  ('新概念二', 70, '["bullfight n. 斗牛","danger n. 危险","symbol n. 符号","charge v. 冲","cape n. 斗篷"]'::text),
  ('新概念二', 71, '["famous adj. 著名的","refuse v. 拒绝","parliament n. 议会","erect v. 建造"]'::text),
  ('新概念二', 72, '["record n. 纪录","attempt n. 尝试","speed n. 速度","confident adj. 有信心的"]'::text),
  ('新概念二', 73, '["record n. 纪录","holder n. 保持者","truant n. 逃学者","unimaginative adj. 缺乏想象力的","shame n. 遗憾","hitchhike v. 搭便车"]'::text),
  ('新概念二', 74, '["limelight n. 聚光灯","precaution n. 预防措施","fan n. 粉丝","shady adj. 阴暗的","sheriff n. 治安官"]'::text),
  ('新概念二', 75, '["signal n. 信号","stamp v. 跺","helicopter n. 直升机","scene n. 现场","survivor n. 幸存者"]'::text),
  ('新概念二', 76, '["fool n. 傻子","broadcast v. 广播","announce v. 宣布","macaroni n. 通心粉","hoax n. 骗局","harvest v. 收获"]'::text),
  ('新概念二', 77, '["heart n. 心脏","successful adj. 成功的","operate v. 做手术","following adj. 下一个的"]'::text),
  ('新概念二', 78, '["entitle v. 命名","dull adj. 枯燥的","act n. 幕","curtain n. 幕布"]'::text),
  ('新概念二', 79, '["parent n. 父母","unaware adj. 不知道的","normal adj. 正常的","bravely adv. 勇敢地"]'::text),
  ('新概念二', 80, '["palace n. 宫殿","extraordinary adj. 非凡的","exhibition n. 展览","iron n. 铁"]'::text),
  ('新概念二', 81, '["escape v. 逃跑","prisoner n. 囚犯","bush n. 灌木","rapidly adv. 迅速地"]'::text),
  ('新概念二', 82, '["monster n. 怪物","sailor n. 水手","sight v. 看到","creature n. 生物","claim v. 声称"]'::text),
  ('新概念二', 83, '["election n. 选举","former adj. 从前的","defeat v. 打败","fanatical adj. 狂热的"]'::text),
  ('新概念二', 84, '["strike n. 罢工","busman n. 公共汽车司机","state n. 状况","agreement n. 协议","relieve v. 减轻"]'::text),
  ('新概念二', 85, '["headmaster n. 校长","pupil n. 学生","retire v. 退休","gift n. 礼物"]'::text),
  ('新概念二', 86, '["control n. 控制","swing v. 转向","bounce v. 弹跳","steeply adv. 陡峭地"]'::text),
  ('新概念二', 87, '["alibi n. 不在场证明","commit v. 犯罪","inspector n. 探长","suspect v. 怀疑","prove v. 证明"]'::text),
  ('新概念二', 88, '["trap v. 困住","mine n. 矿井","rescue v. 营救","drill v. 钻孔","collapse v. 坍塌"]'::text),
  ('新概念二', 89, '["slip n. 口误","tongue n. 舌头","comedy n. 喜剧","present v. 呈现","audience n. 观众"]'::text),
  ('新概念二', 90, '["supper n. 晚餐","fishing n. 钓鱼","net n. 网","consider v. 考虑"]'::text),
  ('新概念二', 91, '["basket n. 篮子","balloon n. 气球","pilot n. 飞行员","frighten v. 使害怕","land v. 着陆"]'::text),
  ('新概念二', 92, '["fast adv. 快","trouble n. 麻烦","tempt v. 引诱"]'::text),
  ('新概念二', 93, '["noble adj. 崇高的","statue n. 雕像","liberty n. 自由","present n. 礼物","sculptor n. 雕塑家"]'::text),
  ('新概念二', 94, '["champion n. 冠军","compete v. 竞争","coach n. 教练"]'::text),
  ('新概念二', 95, '["fantasy n. 幻想","ambassador n. 大使","Dorado n. 黄金国"]'::text),
  ('新概念二', 96, '["dead adj. 死的","return v. 返回","festival n. 节日","honour v. 纪念","lantern n. 灯笼"]'::text)
) as v(book, lesson_no, words) on true
on conflict (family_id, book, lesson_no) do nothing;

-- 导入后自检：应显示两本书的课数与词数
select book, count(*) as 课数, sum(jsonb_array_length(words)) as 词数
from lesson_words group by book order by book;
